### ISSUE TITLE
Compiler error with VS 2013 Express

### ISSUE THREAD

**Issue by YuePan** [fkarb/pythonnet_old#6]
Error   1   The "DllExportAppDomainIsolatedTask" task could not be instantiated from "...\Visual Studio 2013\Projects\pythonnet\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExport.MSBuild.dll". Could not load file or assembly 'RGiesecke.DllExport.MSBuild, Version=1.2.3.29767, Culture=neutral, PublicKeyToken=ad5f9f4a55b5020b' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)  Python.Runtime

Error   2   The "DllExportAppDomainIsolatedTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.  Python.Runtime

**Comment by tonyroberts** [comment]
build using setupwin.py and visual studio 2012, e.g.
python setupwin.py build

**Comment by YuePan** [comment]
It does not solve my problem. I use visual studio 2012 and python 3.3 to compile as suggested. 

D:\Share\pythonnet\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExpo
rt.targets(36,5): error MSB4061: The "DllExportAppDomainIsolatedTask" task coul
d not be instantiated from "D:\Share\pythonnet\packages\UnmanagedExports.1.2.3-
Beta\tools\RGiesecke.DllExport.MSBuild.dll". Could not load file or assembly 'R
Giesecke.DllExport.MSBuild, Version=1.2.3.29767, Culture=neutral, PublicKeyToke
n=ad5f9f4a55b5020b' or one of its dependencies. Operation is not supported. (Ex
ception from HRESULT: 0x80131515) [D:\Share\pythonnet\src\runtime\Python.Runtim
e.csproj]
D:\Share\pythonnet\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExpo
rt.targets(36,5): error MSB4060: The "DllExportAppDomainIsolatedTask" task has
been declared or used incorrectly, or failed during construction. Check the spe
lling of the task name and the assembly name. [D:\Share\pythonnet\src\runtime\P
ython.Runtime.csproj]

**Comment by tonyroberts** [comment]
Hi,

is your D: a network share by any chance? If so can you try building from a local disk?

Regards,
Tony

**Comment by YuePan** [comment]
Hi Tony,

Thank you for your quick response. D: is my local disk. I check the dll, it's there.

I notice it complains "Could Not Find D:\Share\pythonnet\clr.pyd" and "Could Not Find D:\Share\pythonnet\src\runtime\bin\x64\Release\clr.pyd" before the CoreCompile.

Regards,

Yue

**Comment by tonyroberts** [comment]
Hi,

it doesn't need that dll before it compiles, as that is the build output.

Please can you send the exact command line you are using to build and the complete log output.

It will almost certainly be a problem with your setup as the code as it's checked in now does build fine with vs2012 (full version, not express). You should probably try uninstalling all versions of vs you have installed, install a clean version of vs2012 (full not express), clone a clean copy of the pythonnet repo and try again.

Tony

**Comment by YuePan** [comment]
Here's the output --

D:\Share\pythonnet>python setupwin.py build
running build
running build_ext
Microsoft (R) Build Engine version 4.0.30319.17929
[Microsoft .NET Framework, version 4.0.30319.18051]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Build started 1/12/2014 9:21:56 PM.
Project "D:\Share\pythonnet\pythonnet.sln" on node 1 (clrmodule target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "ReleaseWin|x64".
Project "D:\Share\pythonnet\pythonnet.sln" (1) is building "D:\Share\pythonnet\
src\clrmodule\clrmodule.csproj" (2) on node 1 (default targets).
PreBuildEvent:
  del "D:\Share\pythonnet\clr.pyd"
  Could Not Find D:\Share\pythonnet\clr.pyd
Project "D:\Share\pythonnet\src\clrmodule\clrmodule.csproj" (2) is building "D:
\Share\pythonnet\src\runtime\Python.Runtime.csproj" (3) on node 1 (default targ
ets).
PreBuildEvent:
  del "D:\Share\pythonnet\src\runtime\bin\x64\Release\clr.pyd"
  Could Not Find D:\Share\pythonnet\src\runtime\bin\x64\Release\clr.pyd
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output fi
les are up-to-date with respect to the input files.
CoreCompile:
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe /noconfig /unsafe+ /n
  owarn:1701,1702 /nostdlib+ /platform:x64 /define:PYTHON33;UCS2 /highentropyva
- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
  .NETFramework\v4.0\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\
  Reference Assemblies\Microsoft\Framework.NETFramework\v4.0\mscorlib.dll" /re
  ference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NET
  Framework\v4.0\System.Core.dll" /reference:"C:\Program Files (x86)\Reference
  Assemblies\Microsoft\Framework.NETFramework\v4.0\System.dll" /debug:pdbonly
  /optimize+ /out:obj\x64\Release\Python.Runtime.dll /target:library /utf8outpu
  t arrayobject.cs assemblyinfo.cs assemblymanager.cs classderived.cs classbase
  .cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorb
  inder.cs constructorbinding.cs converter.cs debughelper.cs delegatemanager.cs
  delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype
  .cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs int
  erfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.
  cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefu
  nctionobject.cs moduleobject.cs modulepropertyobject.cs monosupport.cs native
  call.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs pyfloat.cs py
  int.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pysequence.cs py
  string.cs pythonengine.cs pythonexception.cs pytuple.cs runtime.cs typemanage
  r.cs typemethod.cs "C:\Users\yupan\AppData\Local\Temp\1.NETFramework,Version
  =v4.0.AssemblyAttributes.cs"
  CopyFilesToOutputDirectory:
  Copying file from "obj\x64\Release\Python.Runtime.dll" to "bin\x64\Release\Py
  thon.Runtime.dll".
  Python.Runtime -> D:\Share\pythonnet\src\runtime\bin\x64\Release\Python.Runti
  me.dll
  Copying file from "obj\x64\Release\Python.Runtime.pdb" to "bin\x64\Release\Py
  thon.Runtime.pdb".
  D:\Share\pythonnet\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExpo
  rt.targets(36,5): error MSB4062: The "RGiesecke.DllExport.MSBuild.DllExportAppD
  omainIsolatedTask" task could not be loaded from the assembly D:\Share\pythonne
  t\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExport.MSBuild.dll. C
  ould not load file or assembly 'file:///D:\Share\pythonnet\packages\UnmanagedEx
  ports.1.2.3-Beta\tools\RGiesecke.DllExport.MSBuild.dll' or one of its dependenc
  ies. The system cannot find the file specified. Confirm that the <UsingTask> de
  claration is correct, that the assembly and all its dependencies are available,
  and that the task contains a public class that implements Microsoft.Build.Fram
  ework.ITask. [D:\Share\pythonnet\src\runtime\Python.Runtime.csproj]
  Done Building Project "D:\Share\pythonnet\src\runtime\Python.Runtime.csproj" (d
  efault targets) -- FAILED.

Done Building Project "D:\Share\pythonnet\src\clrmodule\clrmodule.csproj" (defa
ult targets) -- FAILED.

Done Building Project "D:\Share\pythonnet\pythonnet.sln" (clrmodule target(s))
-- FAILED.

Build FAILED.

"D:\Share\pythonnet\pythonnet.sln" (clrmodule target) (1) ->
"D:\Share\pythonnet\src\clrmodule\clrmodule.csproj" (default target) (2) ->
"D:\Share\pythonnet\src\runtime\Python.Runtime.csproj" (default target) (3) ->
(RGieseckeDllExport target) ->
  D:\Share\pythonnet\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllEx
port.targets(36,5): error MSB4062: The "RGiesecke.DllExport.MSBuild.DllExportAp
pDomainIsolatedTask" task could not be loaded from the assembly D:\Share\python
net\packages\UnmanagedExports.1.2.3-Beta\tools\RGiesecke.DllExport.MSBuild.dll.
 Could not load file or assembly 'file:///D:\Share\pythonnet\packages\Unmanaged
Exports.1.2.3-Beta\tools\RGiesecke.DllExport.MSBuild.dll' or one of its depende
ncies. The system cannot find the file specified. Confirm that the <UsingTask>
declaration is correct, that the assembly and all its dependencies are availabl
e, and that the task contains a public class that implements Microsoft.Build.Fr
amework.ITask. [D:\Share\pythonnet\src\runtime\Python.Runtime.csproj]

```
0 Warning(s)
1 Error(s)
```

Time Elapsed 00:00:00.88
Traceback (most recent call last):
  File "setupwin.py", line 63, in <module>
    "build_ext" : PythonNET_BuildExt
  File "C:\Python33\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python33\lib\distutils\dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "C:\Python33\lib\distutils\dist.py", line 948, in run_command
    cmd_obj.run()
  File "C:\Python33\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "C:\Python33\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python33\lib\distutils\dist.py", line 948, in run_command
    cmd_obj.run()
  File "C:\Python33\lib\distutils\command\build_ext.py", line 353, in run
    self.build_extensions()
  File "C:\Python33\lib\distutils\command\build_ext.py", line 462, in build_exte
nsions
    self.build_extension(ext)
  File "setupwin.py", line 42, in build_extension
    subprocess.check_call(" ".join(cmd))
  File "C:\Python33\lib\subprocess.py", line 547, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\windows\Microsoft.NET\Framework64\v4.
0.30319\msbuild.exe pythonnet.sln /p:Configuration=ReleaseWin /p:Platform=x64 /p
:DefineConstants="PYTHON33;UCS2" /t:clrmodule' returned non-zero exit status 1

**Comment by tonyroberts** [comment]
Hi,

ah, I see the problem now. It's because you're using the 64 bit version of visual studio, but the RGiesecke.DllExport dlls are the 32 bit versions and that's why they won't load.

You need to either install the 32 bit version of visual studio or get the 64 bit dlls. You can get them from NuGet:  http://www.nuget.org/packages/UnmanagedExports/1.2.3-Beta

Regards,
Tony

**Comment by YuePan** [comment]
Cool. It works perfect with UnmanagedExports 1.2.6 on Windows 8.1 64 bits. Somehow, the packages.config of clrmodule still contain a reference to 1.2.3-Beta. When it was changed as following, it stops to download the dll version 1.2.3-beta

<packages>
  <package id="UnmanagedExports" version="1.2.6" targetFramework="net40" />
</packages>

**Comment by tonyroberts** [comment]
Cool. Glad you were able to get it working. I'll leave it as 1.2.3-beta for now as that's what the main project this is forked from uses.
